name: CI
'on':
    - push
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v1
                with:
                    fetch-depth: 1
            -
                name: Set up Python 3.8
                uses: actions/setup-python@v1
                with:
                    python-version: 3.8
            -
                uses: Gr1N/setup-poetry@v4
            -
                uses: actions/cache@v1
                id: cache
                with:
                    path: ~/.cache/pypoetry/virtualenvs
                    key: '${{ runner.os }}-poetry-${{ hashFiles(''poetry.lock'') }}'
                    restore-keys: |
                        ${{ runner.os }}-poetry-
            -
                run: poetry install # if: steps.cache.outputs.cache-hit != 'true'
            -
                name: Pytest
                run: poetry run pytest --cov . 
                if: always()
            -
                uses: codecov/codecov-action@v1
                with:
                    file: ./coverage.xml
                    flags: unittests
                    name: codecov-umbrella
                    verbose: true
                if: always()
            -
                name: Black
                run: poetry run black . --check -l 81
            -
                name: Mypy
                run: poetry run mypy .
                if: always()
            -
                name: Pylint
                run: poetry run pylint .
                if: always()
