name: CI
'on':
    - push
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v1
                with:
                    fetch-depth: 1
            -
                name: Set up Python 3.8
                uses: actions/setup-python@v1
                with:
                    python-version: 3.8
            -
                name: Install Poetry
                uses: dschep/install-poetry-action@v1.2
            -
                name: Cache Poetry virtualenv
                uses: actions/cache@v1
                id: cache
                with:
                    path: ~/.virtualenvs
                    key: 'poetry-${{ hashFiles(''**/poetry.lock'') }}'
                    restore-keys: |
                        poetry-${{ hashFiles('**/poetry.lock') }}
            -
                name: Set Poetry config
                run: |
                    poetry config settings.virtualenvs.in-project false
                    poetry config settings.virtualenvs.path ~/.virtualenvs
            -
                name: Install Dependencies
                run: poetry install
                if: steps.cache.outputs.cache-hit != 'true'
            -
                name: Black
                run: poetry run black . --check -l 81
            -
                name: Mypy
                run: poetry run mypy .
                if: always()
            -
                name: Pylint
                run: poetry run pylint .
                if: always()
            -
                name: Pytest
                run: poetry run pytest --cov . -n 2
                if: always()
            -
                uses: codecov/codecov-action@v1
                with:
                    file: ./coverage.xml
                    flags: unittests
                    name: codecov-umbrella
                    verbose: true
